### ISSUE TITLE
Hyprland not executing

### ISSUE THREAD

**Issue by morpheuslord** [SolDoesTech/hyprland#5]
At the last after all the installation is done, I am facing this error.
![Screenshot 2023-05-28 165931](https://github.com/SolDoesTech/hyprland/assets/70637311/436a1926-dd4f-4986-8544-992ed86afe43)
What should I do ??

**Comment by SolDoesTech** [comment]
try this: sudo pacman -S hyprland

**Comment by morpheuslord** [comment]
Then?. I am stuck in a login loop cause of this

https://github.com/SolDoesTech/hyprland/assets/70637311/c091420c-2e08-4fc4-87c8-1c89b5f23789

**Comment by SolDoesTech** [comment]
Is this running on a VM?

**Comment by morpheuslord** [comment]
> Is this running on a VM?

yes

**Comment by sumit-modak** [comment]
![Screenshot_2023-06-26_19:55:01](https://github.com/SolDoesTech/hyprland/assets/96831387/22d6bc6c-e55f-4c50-82a6-88e2a6f26f0c)
bro facing same issue

**Comment by SolDoesTech** [comment]
Hello, Hyprland is not meant to run on a VM, the only way I was able to get it to work on a VM is with a GPU passthrough. 3D acceleration could work but its super slow and some programs wont open.

**Comment by ghost** [comment]
I rebooted the system and it worked

**Comment by SolDoesTech** [comment]
very nice, is it usable? if so please provide some details about your VM and your GPU. Thanks!

**Comment by ghost** [comment]
Black lines are coming throughout the whole screen. I think its hyprland's problem. 
GPU - Integrated GPU inside Ryzen 5600G
VM - QEMU/KVM with Virt-Manager

**Comment by SolDoesTech** [comment]
Yeah I would agree its a hyprland issue https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#vm

**Comment by ghost** [comment]
I didn't knew about that thanks for the info. BTW really appreciate your work though. It looks really cool

**Comment by SolDoesTech** [comment]
Thank you, glad you like it :)

**Comment by morpheuslord** [comment]
Then I will try it with a live install

**Comment by khar34** [comment]
When i try to launch Hyprland, it always results in this error [libseat] [libseat/backend/seatd.c:64 could not connect to socket /run/seatd.sock: No such file or directory
When i solved the no such file problem, it will result in new error 
[libseat] [libseat/backend/seatd.c:64 could not connect to socket /run/seatd.sock: Permission denied
What should I do, should I just reinstall Hyprland, this is my first time install arch linux so

**Comment by RhaZenZ0** [comment]
> 

Check user permissions: If you encounter the "Permission denied" error after ensuring that the socket file exists, make sure that the current user has the necessary permissions to access the socket. The socket file should be owned by the same user running the Wayland compositor or should have appropriate read/write permissions for all users. You can try running the compositor with elevated privileges (using sudo) temporarily to see if the error persists.

**Comment by ghost** [comment]
Please close this issue
