### ISSUE TITLE
auto-update? 

### ISSUE THREAD

**Issue by gumbobrot** [SolDoesTech/hyprland#7]
yo is there like a thing that updates the system when the original hyprland repo is updated? Or will the system update when you run yay -Sy(u)? And btw how do i change the keyboard layout, when i try to change the value which is set to us and change it to de i dont understand how to save it or what exact command is like doing what, im really confused because everything is currently set for a us keyboard and because there are so many binds?

**Comment by umair-moon-malik** [comment]
u can change ur keyboard lang in .config/hypr/hyprland.conf

**Comment by umair-moon-malik** [comment]
u can change ur keyboard lang in .config/hypr/hyprland.conf

**Comment by pipitaf** [comment]
If it can help anyone you can do that in .config/hypr/hyprland.conf by line 27, its called kb_layout =

**Comment by gumbobrot** [comment]
thanks for the answers i got it, just didnt understand how vim works
