### ISSUE TITLE
decoration : blur_new_optimizations value error

### ISSUE THREAD

**Issue by ericlin1231** [SolDoesTech/hyprland#9]
I follow your video(https://www.youtube.com/watch?v=lfUWwZqzHmA) procedure to install archlinux and hyprland but when I enter the desktop the error occur. The warning said " error setting value \<on\> for field \<decoration : blur_new_optimizations\> :No such field.Hyprland may not work correctly" . How can I solve the problem

**Comment by umair-moon-malik** [comment]
the configuration file format for hyprland changed... this config file is old... please refer to hyprland wiki and try fixing ur configuration file....

lemma know if u need any more help...
